# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            React Hot Loader
tagline:          Live-reloading your React components since 2014
url:              http://github.com/gaearon/react-hot-loader
paginate:         1
baseurl:          http://gaearon.github.io/react-hot-loader/
author:
  name:           Dan Abramov
  url:            https://twitter.com/dan_abramov
  email:          dan.abramov@me.com

# Custom vars
version:          0.2.0
github:
  repo:           http://github.com/gaearon/react-hot-loader
